# Generated by Django 5.0.4 on 2026-04-11 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('flipped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('H', 'Heads'), ('T', 'Tails'), ('U', 'Unknown')], default='U', max_length=1)),
                ('image', models.ImageField(upload_to='coinflipper/')),
            ],
        ),
    ]
