# Generated by Django 5.0.4 on 2026-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinflipper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFlipStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('heads', models.IntegerField(default=0)),
                ('tails', models.IntegerField(default=0)),
                ('unknown', models.IntegerField(default=0)),
                ('longest_run_heads', models.IntegerField(default=0)),
                ('longest_run_tails', models.IntegerField(default=0)),
                ('current_run_result', models.CharField(default='U', max_length=1)),
                ('current_run_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='coinflip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coinflipper/'),
        ),
    ]
