# Generated by Django 5.0.4 on 2026-04-26 16:07

import coinflipper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinflipper', '0002_coinflipstats_alter_coinflip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinflip',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coinflip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=coinflipper.models._flip_image_path),
        ),
    ]
