# Generated by Django 5.0.4 on 2026-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinflipper', '0003_coinflip_checked_alter_coinflip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='coinflip',
            name='coin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
