# Generated by Django 5.0.4 on 2024-05-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(default='nobody', max_length=127),
            preserve_default=False,
        ),
    ]
