# Generated by Django 4.2.7 on 2023-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interval_timer', '0002_alter_schedule_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='easy_description',
            field=models.CharField(default='Easy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='hard_description',
            field=models.CharField(default='Hard', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='cooldown_description',
            field=models.CharField(default='Cooldown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='warmup_description',
            field=models.CharField(default='Warmup', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
