# Generated by Django 5.0 on 2023-12-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interval_timer', '0004_remove_schedule_profile_schedulecreator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='interval_timer.schedulecreator'),
            preserve_default=False,
        ),
    ]
