# Generated by Django 4.2.7 on 2023-11-12 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invitee_email", models.EmailField(max_length=254)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("number_in_room", models.SmallIntegerField(default=1)),
                ("offer", models.JSONField(blank=True, null=True)),
                ("answer", models.JSONField(blank=True, null=True)),
                ("link_sent", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="live_chat_webRTC.profile",
                    ),
                ),
            ],
        ),
    ]
